BEGIN;
DROP TABLE IF EXISTS eod_jobs CASCADE;
DROP TABLE IF EXISTS system_events CASCADE;
DROP TABLE IF EXISTS screening_results CASCADE;
DROP TABLE IF EXISTS bacen_reports CASCADE;
DROP TABLE IF EXISTS iof_computations CASCADE;
DROP TABLE IF EXISTS classifications CASCADE;
COMMIT;
