BEGIN;
DROP TABLE IF EXISTS ssis CASCADE;
DROP TABLE IF EXISTS bic_records CASCADE;
DROP TABLE IF EXISTS calendar_holidays CASCADE;
DROP TABLE IF EXISTS calendars CASCADE;
DROP TABLE IF EXISTS currencies CASCADE;
COMMIT;
