// pkg/bacen/codegen — generates pkg/bacen/codes_full.go from the CSV
// source-of-truth at data/bacen/nature-codes-circ-3690-vYYYYMMDD.csv.
//
// Invoke via `go generate ./pkg/bacen/...` (see codes_full.go for the
// //go:generate directive). Not meant to be run by hand outside CI / dev loop.
//
// Output is deterministic — runs are byte-stable when the input CSV is unchanged,
// so the generated file can be committed to git without churn.
package main

import (
	"encoding/csv"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"text/template"
	"time"
)

type natureCode struct {
	Code           string
	Category       string
	Subcategory    string
	DescriptionPT  string
	DescriptionEN  string
	Direction      string
	DocRequirement []string
	IOFOpType      string
	Active         bool
}

const fileTmpl = `// Code generated by pkg/bacen/codegen — DO NOT EDIT.
// Source: {{ .Source }}
// Generated: {{ .GeneratedAt }}
// Count: {{ len .Codes }}

package bacen

// NatureCodeFull is the rich BACEN Circular 3.690 entry from the generated catalogue.
// Distinct from the legacy NatureCode (Code+Description+Nature) which remains
// the public type consumed by the Classifier; NatureCodeFull is the source of
// truth that the Classifier (and DEC submission, IOF lookup, etc.) read from.
type NatureCodeFull struct {
	Code           string
	Category       string
	Subcategory    string
	DescriptionPT  string
	DescriptionEN  string
	Direction      string
	DocRequirement []string
	IOFOpType      string
	Active         bool
}

// AllNatureCodes is the full catalogue indexed by code.
//
// Lookup ordering: deterministic alphabetical-by-code at code-generation time.
var AllNatureCodes = map[string]NatureCodeFull{
{{- range .Codes }}
	"{{ .Code }}": {
		Code:           "{{ .Code }}",
		Category:       "{{ .Category }}",
		Subcategory:    "{{ .Subcategory }}",
		DescriptionPT:  {{ printf "%q" .DescriptionPT }},
		DescriptionEN:  {{ printf "%q" .DescriptionEN }},
		Direction:      "{{ .Direction }}",
		DocRequirement: []string{ {{ range $i, $d := .DocRequirement }}{{ if $i }}, {{ end }}"{{ $d }}"{{ end }} },
		IOFOpType:      "{{ .IOFOpType }}",
		Active:         {{ .Active }},
	},
{{- end }}
}

// CountByCategory returns the number of codes per top-level category.
// Convenience helper for diagnostics + dashboards.
func CountByCategory() map[string]int {
	out := make(map[string]int)
	for _, c := range AllNatureCodes {
		if c.Active {
			out[c.Category]++
		}
	}
	return out
}

// FullByCode returns the rich entry for a BACEN code, or false on miss.
// Use this when you need direction / doc requirements / IOF op type;
// the legacy Classifier.ByCode keeps returning the slim NatureCode shape.
func FullByCode(code string) (NatureCodeFull, bool) {
	n, ok := AllNatureCodes[code]
	return n, ok
}
`

func main() {
	in := flag.String("input", "", "input CSV path (required)")
	out := flag.String("output", "", "output Go file path (required)")
	flag.Parse()

	if *in == "" || *out == "" {
		log.Fatalf("usage: codegen --input <csv> --output <go-file>")
	}

	f, err := os.Open(*in)
	if err != nil {
		log.Fatalf("open input: %v", err)
	}
	defer f.Close()

	codes, err := parseCSV(f)
	if err != nil {
		log.Fatalf("parse: %v", err)
	}

	sort.Slice(codes, func(i, j int) bool { return codes[i].Code < codes[j].Code })

	tmpl, err := template.New("file").Parse(fileTmpl)
	if err != nil {
		log.Fatalf("template parse: %v", err)
	}

	outFile, err := os.Create(*out)
	if err != nil {
		log.Fatalf("create output: %v", err)
	}
	defer outFile.Close()

	if err := tmpl.Execute(outFile, struct {
		Source      string
		GeneratedAt string
		Codes       []natureCode
	}{
		Source:      filepath.Base(*in),
		GeneratedAt: time.Now().UTC().Format("2006-01-02T15:04:05Z"),
		Codes:       codes,
	}); err != nil {
		log.Fatalf("template execute: %v", err)
	}

	log.Printf("wrote %d codes to %s", len(codes), *out)
}

func parseCSV(r io.Reader) ([]natureCode, error) {
	cr := csv.NewReader(r)
	cr.TrimLeadingSpace = true
	header, err := cr.Read()
	if err != nil {
		return nil, fmt.Errorf("header: %w", err)
	}
	idx := indexHeader(header)

	must := []string{"code", "category", "subcategory", "description_pt", "description_en", "direction", "doc_requirement", "iof_op_type", "active"}
	for _, h := range must {
		if _, ok := idx[h]; !ok {
			return nil, fmt.Errorf("missing required column: %s", h)
		}
	}

	out := make([]natureCode, 0, 128)
	line := 1
	for {
		rec, err := cr.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, fmt.Errorf("line %d: %w", line, err)
		}
		line++

		active, err := strconv.ParseBool(rec[idx["active"]])
		if err != nil {
			return nil, fmt.Errorf("line %d active: %w", line, err)
		}

		out = append(out, natureCode{
			Code:           rec[idx["code"]],
			Category:       rec[idx["category"]],
			Subcategory:    rec[idx["subcategory"]],
			DescriptionPT:  rec[idx["description_pt"]],
			DescriptionEN:  rec[idx["description_en"]],
			Direction:      rec[idx["direction"]],
			DocRequirement: splitPlus(rec[idx["doc_requirement"]]),
			IOFOpType:      rec[idx["iof_op_type"]],
			Active:         active,
		})
	}
	return out, nil
}

func indexHeader(h []string) map[string]int {
	m := make(map[string]int, len(h))
	for i, name := range h {
		m[strings.TrimSpace(name)] = i
	}
	return m
}

func splitPlus(s string) []string {
	s = strings.TrimSpace(s)
	if s == "" {
		return nil
	}
	parts := strings.Split(s, "+")
	for i := range parts {
		parts[i] = strings.TrimSpace(parts[i])
	}
	return parts
}
